### ISSUE TITLE
Graphs and tables not in specs

### ISSUE THREAD

**Issue by tvroylandt** [rfortherestofus/pschousing#41]
Some graphs and tables from last year report are not in the current specs. Is it all ok or did i forgot to put them somewhere ?

![image](https://user-images.githubusercontent.com/28248895/89315137-c94f6800-d67a-11ea-824f-d47b39c4c4a5.png)

![image](https://user-images.githubusercontent.com/28248895/89316015-d456c800-d67b-11ea-9661-f474a2fecc43.png)

![image](https://user-images.githubusercontent.com/28248895/89316051-dde03000-d67b-11ea-9e83-0c435110247d.png)

**Comment by dgkeyes** [comment]
No, these don't need to be included. You only need to include those listed in [this Word document](https://github.com/rfortherestofus/pschousing/blob/master/inst/specs/Housing%20Data%20Profiles%20PDF%20metrics_2020-07-16_For%20Consultants.docx).
